### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by fmarletaz** [BenoitMorel/GeneRax#35] opened 2020-08-04 09:07 UTC
Dear Benoît, 

Our institute deployed a new server and shut down the previous one, so I had to recompile generax. I tried the conda version but our new system is using AMD so I am not sure whether the conda version is compiled under AVX or not, and also, I have the conda version seems to stall in the process after the  step: 
`[00:00:50] [Initialization] All the families will first be optimized with sequences only`
nothing more is printed. Is there a way to know what is the progress of the job. 

So, I tried to compile directly and I encounter the error below. What do you think? 

```[ 45%] Built target pllmodutil_obj
[ 45%] Building C object ext/pll-modules/libs/libpll/src/CMakeFiles/pll_obj.dir/core_derivatives_sse.c.o
Scanning dependencies of target mpi-scheduler
[ 46%] Building C object ext/pll-modules/libs/libpll/src/CMakeFiles/pll_obj.dir/core_likelihood_sse.c.o
[ 47%] Building CXX object ext/MPIScheduler/src/CMakeFiles/mpi-scheduler.dir/main.cpp.o
c++: fatal error: no input files
compilation terminated.
/bin/sh: -pthread: command not found
make[2]: *** [ext/MPIScheduler/src/CMakeFiles/mpi-scheduler.dir/build.make:63: ext/MPIScheduler/src/CMakeFiles/mpi-scheduler.dir/main.cpp.o] Error 127
make[1]: *** [CMakeFiles/Makefile2:861: ext/MPIScheduler/src/CMakeFiles/mpi-scheduler.dir/all] Error 2
```

Thanks!

**Comment by BenoitMorel** [comment] 2020-08-04 11:56
Dear Ferdinand,

Regarding AVX: our programs are automatically compiled/run with the best available and supported instructions set (AVX, AVX2, SSE or none). I don't think that we print the information in the logs, but you can get it from the compilation logs, during the cmake step.

 Regarding the stalling process: this step is run when you don't provide starting gene trees. GeneRax infers them by calling raxml-ng. This step can be quite long, depending on the size of your MSAs, and in particular on the number of taxa in the biggest family. You can check how many of the families were already processed in the file `generax/raxml_light_0/logs.txt`. Unfortunately, I don't think you can check individual jobs progress, but I can add that in the next release. 
If this really gets too long, you can alternatively use ParGenes (https://github.com/BenoitMorel/ParGenes), which also infers gene trees using raxml-ng, but with a better parallelization scheme, and with more logs to monitor the progress. Then you could use those starting gene trees to skip this step in GeneRax. But  that would add one more step in your analysis (and this is always exhausting!), so I would rather wait for this GeneRax step to finish.

Regarding the compilation error: I accidentally ran into the exact same issue when compiling another tool. It seems to be an error in cmake (it adds an invalid flag when compiling with MPI), and there is no way for solving this from our side. I recommend to try installing an older or more recent version of cmake. See https://gitlab.kitware.com/cmake/cmake/-/issues/18448. If I understand correctly, the bug is present between cmake 3.10.0 and 3.12.3. 

I hope this helps,
Benoit

**Comment by fmarletaz** [comment] 2020-08-06 06:37
Hi -  Thanks a lot for the quick feedback, that's really helpful. I checked the log you mention. I looks like most of trees were done, but a few (about 20) seem to take a really long time to finish. I might try to exclude these corresponding families and relaunched. 
I actually have a set of trees for most of these gene families, and I tried to run generax with them, but I got the following error :
`generax: /opt/conda/conda-bld/generax_1595442213485/work/ext/pll-modules/libs/libpll/src/parse_utree.y:500: utree_wraptree: Assertion `inner_index == tip_count + inner_count' failed.`
Should I remove the bootstraps from the trees? Is there another problem with the trees?

**Comment by BenoitMorel** [comment] 2020-08-06 20:39
Yes, unfortunately these few trees that take much more time than the rest
are a typical computational issue that we still don't know how to solve,
even with parallelization (because we can't really parallelize)... If you
can afford excluding them for the analysis, that is indeed the easiest
solution.

Having support values in the tree should not cause any issue (they are just
ignored). I don't know what the issue is, but here are some ideas of what
could go wrong:
- the format is not newick
- the gene tree is rooted (which is actually something I should support,
I'll try to add it for the next release)
- the gene tree is not binary (contains polytomies). This typically happens
when they were inferred with FastTree
- they are several trees in the newick file

If this does not help, can you send me a few trees that cause this error
message?

Best,
Benoit

**Comment by fmarletaz** [comment] 2020-08-14 08:07
Hi Benoît, 

Thanks for all your advices. I managed to filter my families and to provide a set of trees, and I manage to get it to work on one datasets. However, I am still having problems with other datasets : 
`slurmstepd: error: Detected 5 oom-kill event(s) in step 341806.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.`
This error seems to be memory related. I am giving 10Gb of memory per process (per core) and 64 processes. Is that related to the size of my alignments, some of them are fairly large (500 sequences). 
Thanks for your comments!

**Comment by BenoitMorel** [comment] 2020-08-14 09:00
Hi Ferdinand,

Do you mean that GeneRax needs 10Gb per process for this dataset?
I would not expect such a memory consumption, even for 500 sequences, but
let's figure it out.
Can you give me:
- the number of gene families
- the number of taxa in the species tree
- the maximal size of the sequences (number of sites) for the families with
large number of sequences
- the substitution model you use
and send me the logs of the failing run?

Benoit

**Comment by fmarletaz** [comment] 2020-08-14 09:33
Hi Benoît,

Thanks. I just realised this error was caused by the first line of the families file (`[FAMILIES]`)  being inadvertently removed, so the memory was not the issue. 
To answer you anyway, I have 9536 gene families, with at most 248 (I cut the families with more genes than that) and at most 13138 positions in the alignment. Model is LG+G. I am rerunning now, it seems to work.
I have another question: when a run is interrupted, can it be restarted? 
Also, I noticed the option `--per-family-rates` and `--per-species-rates`, are those referring to the rate of substitutions or the rate of duplication and losses. Are these options going to making the computation much more difficult?  I am asking because for what I am trying to do, the possibility to account to duplication rates would be rather interesting. 
Thanks and sorry for the confusion.

**Comment by BenoitMorel** [comment] 2020-08-14 12:25
Great that it works!

Yes, there is a checkpoint system such that you can restart a run after an
interruption.

The options correspond to rates of duplication and losses.
Per family rates don't make the computation more difficult, but per species
branch rates do (for the rates optimization step).
From experiments on simulations, my impression is that the three different
modes do not affect the accuracy much. But the per-family rates mode also
outputs the estimated rates for each family, which can be interesting.
Please note that the duplication/loss rates are not exactly "rates", in the
sense that they are not the expected number of events per unit of time. If
you need more information, please let me know.
I will add these information in the wiki next soon.

Depending on what you are trying to do, do not hesitate to tell me if some
additional output/information could be useful to you and other users. We
realized that we focused too much on the gene tree topology accuracy
without thinking enough about what really interests users.

Best,
Benoit

**Comment by BenoitMorel** [comment] 2020-11-02 12:22
I close the issue. Please reopen if you need further help!

**Closed by BenoitMorel** 2020-11-02 12:22 UTC
