### ISSUE TITLE
No valid families?

### ISSUE THREAD

**Issue by KyleTDavid** [BenoitMorel/GeneRax#67] opened 2023-09-08 18:29 UTC
Hello,

I am getting an error where none of my families appear to be valid. I've checked the alignments for forbidden characters and double checked the model notation but can't find any obvious culprits. Attached are my species tree, families file, and example alignment, any idea what might be going on? The command I used was:
`generax -f testfamilies.txt -s SpeciesTree.nwk`

[testfamilies.txt](https://github.com/BenoitMorel/GeneRax/files/12562745/testfamilies.txt)
[SpeciesTree.txt](https://github.com/BenoitMorel/GeneRax/files/12562735/SpeciesTree.txt)
[OG0000389_aligned.txt](https://github.com/BenoitMorel/GeneRax/files/12562750/OG0000389_aligned.txt)

**Comment by BenoitMorel** [comment] 2023-09-08 20:00
Hello Kyle,
I don't see anything suspicious at first sight. Can you also send me the
mapping file and the starting gene tree for this particular family, such
that I can reproduce? Thanks!
Benoit

Le ven. 8 sept. 2023 à 20:29, Kyle David ***@***.***> a
écrit :

**Comment by KyleTDavid** [comment] 2023-09-08 20:16
Here you go, thanks so much!
[OG0000389.link.txt](https://github.com/BenoitMorel/GeneRax/files/12563481/OG0000389.link.txt)
[OG0000389.treefile.txt](https://github.com/BenoitMorel/GeneRax/files/12563483/OG0000389.treefile.txt)

**Comment by BenoitMorel** [comment] 2023-09-08 21:14
I'm not quite sure why yet, but in:
"g001762.m1|Candida_orthopsilosis_90–125"
The character "–" is rejected. Also it appears differently in the gene tree
in my text editor. I will stop now and I will have another look on Monday.
But I'd suggest replacing this character with another as a potential quick
fix

Le ven. 8 sept. 2023 à 22:17, Kyle David ***@***.***> a
écrit :

**Comment by KyleTDavid** [comment] 2023-09-09 16:51
Thanks for the response! Unfortunately, this did not solve my issue. It's also worth noting that another gene family in my test example does not contain the Candida_orthopsilosis_90–125 taxon, and is still marked as invalid. Here are the updated files I used after substituting the "–" character, whenever you get the chance. 
[OG0000389_aligned.fa.txt](https://github.com/BenoitMorel/GeneRax/files/12566275/OG0000389_aligned.fa.txt)
[OG0000389.link.txt](https://github.com/BenoitMorel/GeneRax/files/12566276/OG0000389.link.txt)
[OG0000389.treefile.txt](https://github.com/BenoitMorel/GeneRax/files/12566277/OG0000389.treefile.txt)
[testfamilies.txt](https://github.com/BenoitMorel/GeneRax/files/12566282/testfamilies.txt)
[SpeciesTree.nwk.txt](https://github.com/BenoitMorel/GeneRax/files/12566283/SpeciesTree.nwk.txt)

**Comment by BenoitMorel** [comment] 2023-09-11 13:24
Hi again,

I had to apply the following modifications to the files:
- add the ".txt" extensions in the family file
- replace GTR with a protein model (GTR is a DNA model, cf raxml-ng
documentation). The error message is a bit misleading, we only detected
that the alignment is invalid, but in fact the model is incorrect
- replace "___" with "_" in two gene tree labels that were not matching the
alignment file
- map the genes C3_03210W_A| and C4_02660W_A| to an arbitrary species (ofc
you'll have to map it to the right species) in the mapping file

GeneRax should be able to help you to fix the mismatches in your other
files. But let me know if you still encounter any problems.

Also, the dataset will be quite challenging to analyse (in terms of
runtime), because you really have a lot of species.

Benoit


Le sam. 9 sept. 2023 à 18:51, Kyle David ***@***.***> a
écrit :

**Comment by KyleTDavid** [comment] 2023-09-11 15:48
Thanks so much for your quick and detailed response, unfortunately I am not able to replicate. I have confirmed that all genes are found in the mapping file, and all species in the mapping file
 are present in the species tree. I have also replaced the model and removed extra "_"s. I'll attach the directory I am working out of, please let me know what I'm missing whenever you get the chance. 

[generax_play.zip](https://github.com/BenoitMorel/GeneRax/files/12578116/generax_play.zip)

**Comment by BenoitMorel** [comment] 2023-09-11 21:05
I get the message I got from the very first iteration:

[00:00:00] Filtering invalid families...
invalid label: g001762.m1|Candida_orthopsilosis_90–125
Error in family OG0000389: Some labels in the MSAs contain invalid
characters
WARNING!!! Found 1 invalid families (they will be discarded from the
analysis)
[Error] No valid families! Aborting GeneRax

The dash in "90–125" looks weird again in my text editor (in two labels).
Then there are still mismatches between the gene tree and the MSA, eg:
g006616.m1|Schwanniomyces_sp._NRRL_Y_7430
g006616.m1|Schwanniomyces_sp._NRRL_Y-7430

It's curious that you don't get an explicit message, on my laptop GeneRax
tells me where the mismatches are



Le lun. 11 sept. 2023 à 17:48, Kyle David ***@***.***> a
écrit :

**Comment by KyleTDavid** [comment] 2023-09-11 22:09
Sorry to keep bothering you with this, I've tried on two different machines using fresh Conda installations and am unable to get things running, my error log is as follows:
```[00:00:00] Filtering invalid families...

Error in family OG0000389: Cannot read alignment file (file exists but is invalid)
WARNING!!! Found 1 invalid families (they will be discarded from the analysis)
[Error] No valid families! Aborting GeneRax```
would you happen to still have the files you used when you got it to run?

**Comment by BenoitMorel** [comment] 2023-09-12 11:29
Here you go:
tar -xzf kyle.tar.gz
cd kyle
generax -s SpeciesTree.nwk -f testfamilies.txt

Maybe there is some bug that has been fixed in the git repository and not
in the bioconda yet? The version on bioconda is older...



Le mar. 12 sept. 2023 à 00:09, Kyle David ***@***.***> a
écrit :

**Comment by KyleTDavid** [comment] 2023-09-12 14:12
Sorry, did you include the actual tarball? It's not showing up for me

**Comment by BenoitMorel** [comment] 2023-09-12 17:18
That's weird, I can see it in the mailing list but not in the github issue. What about now?:
[kyle.tar.gz](https://github.com/BenoitMorel/GeneRax/files/12589148/kyle.tar.gz)

**Closed** 2023-09-12 18:36 UTC
